### ISSUE TITLE
Whoa there! Error

### ISSUE THREAD

**Issue by ModestGoblin** [ModestGoblin/github-notifications#10]
<img width="390" alt="screen shot 2016-02-11 at 8 39 25 pm" src="https://cloud.githubusercontent.com/assets/9078428/12996702/3b2b7fe8-d100-11e5-8b04-299b45a717cd.png">
If you choose to get notifications from "popular repositories" it seems to block the pulls made when such a change happens on a repo. I've emailed GitHub contact support, but this might need a bigger work around.

**Comment by ModestGoblin** [comment]
Will try to set updates for every 30s or 1m, so it doesn't initiate whatever rate tracker GitHub has in place.

**Comment by ModestGoblin** [comment]
GitHub support response:
_Sorry for the inconvenience, but the reason for the error is because your plugin is making massive numbers of requests to GitHub and negatively impacting the experience of other users.

If you wish to keep using your plugin, then we suggest switching over to using our api[1] and to reduce the frequency of your requests to stay within our rate limits[2] and [3].

[1] https://developer.github.com/v3/
[2] https://developer.github.com/v3/rate_limit/
[3] https://developer.github.com/v3/#rate-limiting

I hope that helps you get ti working again.

_
What do you think @teovoinea ?

**Comment by teovoinea** [comment]
@ModestGoblin, see if there's a callback in the API so you're not constantly polling their servers. Also consider if you had more users, each polling every 30 seconds/1 min you could easily break the 5000 cap with 100 users leaving their browser on for an hour.

**Comment by ModestGoblin** [comment]
fixed in version 1.2.0!
